TOPLEVEL_LANG = vhdl
SIM=ghdl
PWD=$(shell pwd)


VHDL_SOURCES ?= $(PWD)/../IntConstMultOptTernary_3329_12.vhdl
TOPLEVEL ?= intconstmultoptternary_3329_12
MODULE ?= test_const_mult

WORKDIR=work

COMPILE_ARGS:=-fexplicit
SIM_ARGS:=--fst=$(TOPLEVEL).fst

export COCOTB_REDUCED_LOG_FMT:=1




# yosys:
# 	mkdir $(WORKDIR)
# 	yosys -m ghdl -p 'ghdl --workdir=$(WORKDIR) -fexplicit $(VHDL_SOURCES) -e $(TOPLEVEL); synth_xilinx -flatten -retime; write_verilog $(TOPLEVEL).synth.v'



# show -format pdf -colors 1 -prefix $(TOPLEVEL).synth ; stat



# ghdl expects lower-case!
ifeq ($(SIM), ghdl)
# TOPLEVEL = $(shell echo $(TOPLEVEL) | awk '{print tolower($0)}')
endif

include $(shell cocotb-config --makefiles)/Makefile.inc
include $(shell cocotb-config --makefiles)/Makefile.sim

default:
	mkdir $(WORKDIR)


